#!/bin/sh
set $left h
set $down j
set $up k
set $right l

set $term alacritty
set $menu rofi

exec --no-startup-id dbus-update-activation-environment --all

output * bg /home/alex/.config/sway/wallpaper.svg fill

## Input configuration
    input type:touchpad {
        dwt enabled
        tap enabled
        natural_scroll enabled
        middle_emulation enabled
    }

### Key bindings
    bindsym Mod4+s exec swaylock -i ~/.config/sway/wallpaper.svg --inside-color "F28E5C" --ring-color "E65532" --inside-ver-color "E65532" --ring-ver-color "E65532"
    bindsym Mod4+t exec $term
    bindsym Mod4+n exec firefox
    bindsym Mod4+p exec firefox --private-window
    bindsym Mod4+g exec alacritty -e nvim
    bindsym Mod4+o exec env EDITOR=nvim VISUAL=nvim alacritty -e ranger
    bindsym Mod4+q kill
    bindsym Mod4+d exec $menu -show drun
    bindsym Mod4+Shift+s exec sh -c 'grim -g "$(slurp)" "$HOME/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png"'
    bindsym Mod4+Shift+r exec sh -c 'wf-recorder -g "$(slurp)" -f "$HOME/screenshots/$(date +%Y-%m-%d_%H-%M-%S).mp4"'
    bindsym Mod4+Shift+q exec pkill -INT wf-recorder

    # Reload the configuration file
    bindsym Mod4+Shift+c reload

    # Exit sway (logs you out of your Wayland session)
    bindsym Mod4+Shift+e exit

# Moving around:
    # Move your focus around
    bindsym Mod4+$left focus left
    bindsym Mod4+$down focus down
    bindsym Mod4+$up focus up
    bindsym Mod4+$right focus right

    # Move the focused window with the same command, but add Shift
    bindsym Mod4+Shift+$left move left
    bindsym Mod4+Shift+$down move down
    bindsym Mod4+Shift+$up move up
    bindsym Mod4+Shift+$right move right

# Workspaces:
    # Switch to workspace
    bindsym Mod4+1 workspace number 1
    bindsym Mod4+2 workspace number 2
    bindsym Mod4+3 workspace number 3
    bindsym Mod4+4 workspace number 4
    bindsym Mod4+5 workspace number 5
    bindsym Mod4+6 workspace number 6
    bindsym Mod4+7 workspace number 7
    bindsym Mod4+8 workspace number 8
    bindsym Mod4+9 workspace number 9
    bindsym Mod4+0 workspace number 10
    # Move focused container to workspace
    bindsym Mod4+Shift+1 move container to workspace number 1
    bindsym Mod4+Shift+2 move container to workspace number 2
    bindsym Mod4+Shift+3 move container to workspace number 3
    bindsym Mod4+Shift+4 move container to workspace number 4
    bindsym Mod4+Shift+5 move container to workspace number 5
    bindsym Mod4+Shift+6 move container to workspace number 6
    bindsym Mod4+Shift+7 move container to workspace number 7
    bindsym Mod4+Shift+8 move container to workspace number 8
    bindsym Mod4+Shift+9 move container to workspace number 9
    bindsym Mod4+Shift+0 move container to workspace number 10
    # Note: workspaces can have any name you want, not just numbers.
    # We just use 1-10 as the default.

# Layout stuff:
    # You can "split" the current object of your focus with
    # Mod4+b or Mod4+v, for horizontal and vertical splits
    # respectively.
    bindsym Mod4+b splith
    bindsym Mod4+v splitv
    # Switch the current container between different layout styles
    bindsym Mod4+e layout toggle split
    # Make the current focus fullscreen
    bindsym Mod4+f fullscreen

# Resizing containers:
mode "resize" {
    bindsym $left resize shrink width 10px
    bindsym $down resize grow height 10px
    bindsym $up resize shrink height 10px
    bindsym $right resize grow width 10px
    bindsym Left resize shrink width 10px
    bindsym Down resize grow height 10px
    bindsym Up resize shrink height 10px
    bindsym Right resize grow width 10px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym Mod4+r mode "resize"

# Utilities:
# Special keys to adjust volume via PulseAudio
bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle
# Special keys to adjust brightness via brightnessctl
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+

# Focused window border
client.focused #7f1f00 #7f1f00 #ffffff #7f1f00 #000000


bar {
    swaybar_command waybar
}

exec_always youtube-local &

exec_always wl-copy -c

exec_always rm /home/alex/.bash_history
